services:
  mqtt:
    build: 
      context: ./mqtt
      dockerfile: Dockerfile
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/config:/mosquitto/config:ro
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '9000:9000'
    env_file:
      - ./frontend/.env
    depends_on:
      - backend